### ISSUE TITLE
SQLite v.s. PostgreSQL в dev mode

### ISSUE THREAD

**Issue by victor-yacovlev** [AmatanHead/collective-blog#2]
А зачем тебе postgres в development-mode? 
Для демонстрации работоспособности сделай использование по умолчанию SQLite, а Postgres оставь в production.
На комиссии у тебя не будет времени для того, чтобы еще и базу данных настраивать для демонстрации работоспособности.

**Comment by AmatanHead** [comment]
Вообще, я на комиссии планировал показывать версию, развернутую на heroku. Можно так сделать?

**Comment by victor-yacovlev** [comment]
Это зависит, от того, каким по счету ты будешь показывать проект. Если ближе к концу, когда комиссия уже хочет уходить, то можно, для экономии времени.
А вообще, нужно продемонстрировать воспроизводимость проекта, т.е. показать процесс установки на голую машину (будет предоставлена виртуалка с root-правами).
