### ISSUE TITLE
Capcha

### ISSUE THREAD

**Issue by victor-yacovlev** [AmatanHead/collective-blog#4]
Невозможно зарегистрироваться по причине отсутствия капчи.

 Captcha:
This ReCaptcha is running with DEBUG=True.

```
Обязательное поле.
```

**Comment by AmatanHead** [comment]
Да, гугл поменял политику и теперь рекапча не отображается на локалхосте. Теперь они хотят, чтобы на дебаг-серверах тоже нужно было указывать ключи.

Так что нужно запускать сервер так: `export RECAPTCHA_PUBLIC_KEY='6LcijRkTAAAAAHQDkKW_ks9jgYpqJ9KPq1nfaq4w' && python manage.py runserver`.
